### ISSUE TITLE
Catalina upgrade

### ISSUE THREAD

**Issue by J1vdL** [anojht/synology-cloud-sync-decrypt-tool#11]
Recently upgraded to Catalina and reinstalled latest version of decrypt-tool, installed dependencies and, gave app full access to disk. But app fails to start. Would you have a suggestion? Thanks.

**Comment by anojht** [comment]
Do you get any error messages? Does the icon show up on the dock? What happens when you click the icon?

**Comment by J1vdL** [comment]
No I don’t get an error message. The icon shows up on the dock, but keeps bouncing but nothing happens. I need to use force quit to stop eventually.

**Comment by anojht** [comment]
I am going to compile a new version and release it shortly, please try it when it has been published.

**Comment by anojht** [comment]
I've published a new release. I tested the decryption on my mac running Catalina and the application works fine.

**Comment by J1vdL** [comment]
Thank you! Works fine now on my Mac with Catalina as well.
