### ISSUE TITLE
How do execute/ open the app?

### ISSUE THREAD

**Issue by jonalange** [anojht/synology-cloud-sync-decrypt-tool#14]
I downloaded it and executed the "InstallMeFirst" app.
Finder tells me to reopen the application. But what application?
There is no other in the downloaded folder,  not in my applicationsfolder or anywhere else.

**Comment by anojht** [comment]
Hi, Are you on BigSur? 

I may have to recompile and release for BigSur, but try downloading the application again and running it.

**Comment by jonalange** [comment]
No, on Mojave. 
I think I just do something wrong. I don‘t see an dmg or something that I could open. Only the „install me first“.

**Comment by anojht** [comment]
Sorry for the late reply, have been very busy with work.

Can you try the follow steps:
1. Go to releases and download the osx.zip file from the latest.
2. Extract it.
3. Move the app with the green lock icon to your Applications folder by copying or dragging and dropping.
4. Double click to run the application.

**Comment by jonalange** [comment]
Thanks! 
I feel really dumb now. I downloaded the whole git...
