### ISSUE TITLE
Dark mode compatibility

### ISSUE THREAD

**Issue by seansfkelley** [anojht/synology-cloud-sync-decrypt-tool#2]
Currently, Mojave's dark mode seems to be partially respected such that if it's enabled some of the text turns white:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/2101409/51078902-0657a200-1672-11e9-9d0a-d4fe6b647d13.png">

If you turn it off, things look normal:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/2101409/51078906-13749100-1672-11e9-8d47-3cc8c5cdbd12.png">

I tried to twiddle the font colors a bit but I'm not familiar with Tk and I wasn't able to get it to change appearance. :/

**Comment by anojht** [comment]
Thanks for reporting this, I will have a look and update the repo.

**Comment by anojht** [comment]
I just pushed some commits after fixing this on my Mojave installation, can you confirm this is now fixed?

**Comment by seansfkelley** [comment]
It needs a `# -*- coding: utf-8 -*-` at the top due to a new non-ASCII character in those changes, but after fixing that and installing the new dependencies it works!

**Comment by anojht** [comment]
I am glad it works, I also just pushed commit to change the file to UTF-8, thanks again for bringing this to my attention and for your help!

**Comment by seansfkelley** [comment]
Awesome, thanks for the great tool!
