### ISSUE TITLE
support button?

### ISSUE THREAD

**Issue by transistorgit** [anojht/synology-cloud-sync-decrypt-tool#5]
I got an error on decryption, it said I should use a "support" button. Just found the About Button of the python menu. Clicking on "About Python" there leads to
(syndecrypt-venv) Bernds-MacBook-Pro-2:synology-cloud-sync-decrypt-tool bernd$ python Synology.py
Traceback (most recent call last):
  File "Synology.py", line 345, in <module>
    root.mainloop()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
  File "Synology.py", line 321, in about_dialog
    img = ImageTk.PhotoImage(Image.open("app.gif").resize((128, 128), Image.ANTIALIAS))
  File "/Users/bernd/syndecrypt-venv/lib/python3.7/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app.gif'

I don't know if this is you apps fault, but I couldn't find a support button anyhow.

**Comment by anojht** [comment]
Hello, thanks for reporting this, it appears the support dialog crashes because the app icon is missing in the repo, I thought I had already committed it, but I guess not.

I will push a commit shortly and this should fix this error. The support button just links to the github issue page anyhow. 😛

**Comment by anojht** [comment]
Just pushed the app icon, can you kindly let me know if this is now resolved and you are able to view the support dialog?

**Comment by transistorgit** [comment]
works!
